######################################################################
# Automatically generated by qmake (2.01a) Di Dez 15 11:32:14 2009
######################################################################

TEMPLATE = app
TARGET = jbc
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += javaclass.h
SOURCES += javaclass.cpp main.cpp
